# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Build and publish (test publish and publish on release)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  release:
    types: [published]

jobs:
  deploy:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 wheel twine
        pip install -r requirements.txt
    - if: runner.os == 'Linux'
      name: Set up GCC
      uses: egor-tensin/setup-gcc@v1
      with:
        version: latest
        platform: x64
    - if: runner.os == 'Windows'
      name: Set up MinGW
      uses: egor-tensin/setup-mingw@v2
      with:
       platform: x64
    - name: Build package
      run: python setup.py bdist_wheel
    - if: github.event_name == 'push' || github.event_name == 'pull_request'
      name: Test publish package
      run: |
        python3 -m twine check dist/*
        
    - if: github.event_name == 'release'
      name: Publish package on release
      run: |
        python3 -m twine upload dist/*
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
